name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t arunaap/nodejs-app .
      - name: Publish image to the docker hub
        run: docker push arunaap/nodejs-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull arunaap/nodejs-app:latest
            sudo docker stop nodejs-app-container || true
            sudo docker rm nodejs-app-container || true
            sudo docker run -d -p 5000:5000 --name nodejs-app-container arunaap/nodejs-app
